### ISSUE TITLE
Data directory is non-standard on *nix

### ISSUE THREAD

**Issue by zautumnz** [aeshthetic/Achieve#1]
https://github.com/aeshthetic/Achieve/blob/master/src/App/Utilities.fs#L36

On most Unix-like OSs, the right place to put data is not a directory in `~/`, it's usually `~/.local/share/[directory]`. On Mac, that could also be `~/Library/Application\ Support/[directory]`.

`Environment.SpecialFolder.LocalApplicationData` should work for this on Unix-like platforms: https://github.com/dotnet/runtime/blob/a80e6d4c69fcfa1e17e17130c144a567b23a12a9/src/libraries/System.Private.CoreLib/src/System/Environment.Unix.cs#L137

**Comment by aeshthetic** [comment]
I'll test out `Environment.SpecialFolder.LocalApplicationData` and see how it goes

**Comment by aeshthetic** [comment]
Fixed with f72cfe4
